version: 2
updates:
  - package-ecosystem: cargo
    directory: "/readfeed"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: cargo
    directory: "/benchmark"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10